[package]
name = "todo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
mongodb = "2.7.1"
dotenv = "0.15.0"
tokio = { version = "1.34.0", features = ["full"] }